name: CMake Build with Conan

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Conan
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.18.4'

    - name: Install Dependencies
      run: conan install . --output-folder=build --build=missing

    - name: Configure CMake
      run: |
           cd build
           cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release

    - name: Build with CMake
      run: |
           cd build
           cmake --build .

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Run Executable
      run: |
           cd build
           ./compressor
