# This workflow runs a verification pipeline when a specific type of comment is added to a pull request.
# Usage: Comment "/verification/<module_name>/<pipeline_name>" on a PR to trigger the verification pipeline.
# Example comment: "/verification/small_variant_caller/evaluate_f1"

name: "Run Verification Pipeline"

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  issue_comment:
    types:
      - created
jobs:
  Deploy:
    name: Deploy and Run Verification
    runs-on: ubuntu-latest
    # Only run if it#s a PR and the comment contains /verification
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}
      - name: debug
        run: ls
